version: "3"
services:
  python:
    build: docker/
    volumes:
    - .:/data/
    command: tail -f /var/log/dpkg.log
    # environment:
    #   KODILOCATION: "${KODILOCATION}"
    #   PLEXLOCATION: "${PLEXLOCATION}"
    #   PLEXTOKEN: "${PLEXTOKEN}"
